name: build win

on: 
  workflow_dispatch:
    inputs:
      v8_version:
        description: 'V8 version, see branches of https://chromium.googlesource.com/v8/v8.git'
        required: true
      release_tag:
        description: 'Release tag'
        required: true

env:
  V8_VERSION: ${{ github.event.inputs.v8_version }}

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        arch: [ x64 ]
        toolchain: [ msvc, clang-cl ]

    name: ${{ matrix.toolchain }} + ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Run build script
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%
          set V8_VERSION=${{env.V8_VERSION}}
          set V8_BUILD_ARCH=${{ matrix.arch }}
          set V8_BUILD_TOOLCHAIN=${{ matrix.toolchain }}
          call build_win.cmd

      - uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.arch }}-${{ matrix.toolchain }}
          path: build_output/

  release:
    runs-on: ubuntu-latest
    needs: [build-windows]
    steps:
      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: build_release/artifact
          merge-multiple: true
      
      - name: Display downloaded artifact
        run: |
          cd build_release
          ls -R
          cd ..
      
      - name: Create Release Asset
        run: |
          cd build_release
          mkdir package
          
          # package tgz
          echo =====[ package tgz ]=====
          cd artifact
          for dir in `ls -d */`; do
            dir=${dir%*/}
            tar -vz -cf ../package/$dir.tgz $dir
          done

          # build manifest
          echo =====[ build manifest ]=====
          cd ../package
          xmake l "../../scripts/build_manifest.lua" "*.tgz" "manifest.json"
          
          # collect release files
          echo =====[ collect release files ]=====
          files=build_release/package/manifest.json
          for pkg in *.tgz; do
            pkg_name=`basename $pkg`
            files="$files $pkg_name:build_release/package/$pkg"
          done
          echo "RELEASE_FILES=$files" >> $GITHUB_ENV

          cd ../../
      
      - name: Upload release files
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ inputs.release_tag }}
          tag: ${{ inputs.release_tag }}
          draft: false
          prerelease: false
          gzip: false
          files: ${{ env.RELEASE_FILES }}