name: test artifact

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'release tag'
        required: true
        default: 'test_artifact'

jobs:
  upload-windows:
    strategy:
      fail-fast: false
      matrix:
        arch: [ x64 ]
        toolchain: [ msvc, clang-cl ]

    name: ${{ matrix.toolchain }} + ${{ matrix.arch }}
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Copy artifact
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%
          set ARTIFACT_PATH=artifact/test-windows-${{ matrix.arch }}-${{ matrix.toolchain }}
          mkdir "%ARTIFACT_PATH%"
          copy /Y windows_x64.cmd "%ARTIFACT_PATH%"
          copy /Y LICENSE "%ARTIFACT_PATH%"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-windows-${{ matrix.arch }}-${{ matrix.toolchain }}
          path: artifact/

  release:
    runs-on: ubuntu-latest
    needs: [upload-windows]
    steps:
      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: build_release/artifact
          merge-multiple: true
      
      - name: Display downloaded artifact
        run: |
          cd build_release
          ls -R
          cd ..
      
      - name: Create Release Asset
        run: |
          cd build_release
          mkdir package
          
          # package tgz
          cd artifact
          for dir in `ls -d */`; do
            dir=${dir%*/}
            tar -vz -cf ../package/$dir.tgz $dir
          done

          # build manifest
          cd ../package
          xmake l ../../scripts/build_manifest.lua *.tgz manifest.json
          
          # build release files
          files=build_release/package/manifest.json
          for pkg in *.tgz; do
            pkg_name=`basename $pkg .tgz`
            files="$files $pkg_name:build_release/package/$pkg"
          done
          echo "RELEASE_FILES=$files" >> $GITHUB_ENV

          cd ../../
      
      - name: Upload release files
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ inputs.tag }}
          tag: ${{ inputs.tag }}
          draft: false
          prerelease: false
          files: ${{ env.RELEASE_FILES }}
