name: test artifact

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'release tag'
        required: true
        default: 'test_artifact'

jobs:
  upload-windows:
    strategy:
      fail-fast: false
      matrix:
        arch: [ x64 ]
        toolchain: [ msvc, clang-cl ]

    name: ${{ matrix.toolchain }} + ${{ matrix.arch }}
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Copy artifact
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%
          set ARTIFACT_PATH=artifact/test-windows-${{ matrix.arch }}-${{ matrix.toolchain }}
          mkdir "%ARTIFACT_PATH%"
          copy /Y windows_x64.cmd "%ARTIFACT_PATH%"
          copy /Y LICENSE "%ARTIFACT_PATH%"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-windows-${{ matrix.arch }}-${{ matrix.toolchain }}
          path: artifact/

  release:
    runs-on: windows-latest
    needs: [upload-windows]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: build_release/artifact
          merge-multiple: true
      
      - name: Display downloaded artifact
        run: |
          cd build_release
          ls -R
          cd ..
      
      - name: Create Release Asset
        shell: cmd
        run: |
          cd build_release
          for /d %%a in (*) do (
            tar -vz -cf ziped/%%a.tgz %%a
          )
          cd ..
      
      - name: Upload release files
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ inputs.tag }}
          tag: ${{ inputs.tag }}
          draft: false
          prerelease: false
          files: build_release/ziped/
