name: test artifact

on: workflow_dispatch

jobs:
  upgrade-artifact:
    name: Upgrade artifact
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy artifact
        shell: cmd
        run: |
          mkdir artifact
          copy /Y windows_x64.cmd artifact/
          copy /Y LICENSE artifact/
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./artifact/**/*

  release:
    runs-on: ubuntu-latest
    needs: [upgrade-artifact]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: ./build_release/
      
      - name: Display downloaded artifact
        run: |
          cd build_release/ && ls -R && cd ../
      
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: test_artifact
          release_name: test_artifact
          draft: false
          prerelease: false
      
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build_release/artifact.zip
          asset_name: artifact.zip
          asset_content_type: application/zip
