name: test artifact

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'release tag'
        required: true
        default: 'test_artifact'

jobs:
  upload-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        arch: [ x64 ]
        toolchain: [ msvc, clang-cl ]

    name: ${{ matrix.toolchain }} + ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Copy artifact
        shell: cmd
        run: |
          mkdir artifact/test-windows-${{ matrix.toolchain }}-${{ matrix.arch }}
          copy /Y windows_x64.cmd artifact
          copy /Y LICENSE artifact
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test_artifact
          path: artifact/

  release:
    runs-on: windows-latest
    needs: [upload-windows]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test_artifact
          path: build_release/artifact
      
      - name: Display downloaded artifact
        run: |
          cd build_release
          ls -R
          cd ..
      
      - name: Create Release Asset
        run: |
          cd build_release
          for /d %%a in (*) do (
            tar -vz -cf ziped/%%a.tgz %%a
          )
          cd ..
      
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: test_artifact
          draft: false
          prerelease: false
      
      - name: Upload release files
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: test_artfact
          draft: false
          prerelease: false
          files: build_release/ziped/
